name: RankList
main: com.teozcommunity.teozfrank.ranklist.main.RankList
version: 0.9.0
author: teozfrank
commands:
   ranklist:
      description: This is a list of ranks for our server.
      usage: /<command>
      aliases: [rnklst, ranks]
permissions:
   ranklist.reload:
      description: Allows a user to reload the config.
      default: op
      
